name: 04 - Using Actions 

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actons/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app
    # 0. Checkout the code from the repository
    # 1. Install deps of our react application
    # 2. Execute autmated tests